### ISSUE TITLE
Common Button Style

### ISSUE THREAD

**Issue by Liz-Chung** [BabDeuSilBun/BDSB-frontend#20]
파일: src/styles/button.tsx

작업 내용:
`<BaseBtn></BaseBtn>`
<img width="437" alt="Screen Shot 2024-08-06 at 9 39 29 PM" src="https://github.com/user-attachments/assets/5f35f240-97d9-4162-ac27-ee9ba9427b45">

`<BaseBtnInactive></BaseBtnInactive>`
<img width="438" alt="Screen Shot 2024-08-06 at 9 40 03 PM" src="https://github.com/user-attachments/assets/d6b170c2-ed98-4085-840a-d52a047202a6">

```
<BtnGroup>
  <HalfBtnPurple></HalfBtnPurple>
  <HalfBtnLight></HalfBtnLight>
</BtnGroup>
```
<img width="437" alt="Screen Shot 2024-08-06 at 9 41 45 PM" src="https://github.com/user-attachments/assets/bf1ac852-0700-4709-9e71-35ce66e997db">

`<RoundBtnFilled></RoundBtnFilled>`
<img width="146" alt="Screen Shot 2024-08-06 at 9 42 25 PM" src="https://github.com/user-attachments/assets/f1736e5e-ab73-4ec2-9521-f59ada18b30d">

`<SmallRdBtn></SmallRdBtn>`
active:
<img width="68" alt="Screen Shot 2024-08-06 at 9 42 47 PM" src="https://github.com/user-attachments/assets/3feeebe8-c8ea-4ea8-bd24-02540cbf2f3e">
inactive:
<img width="69" alt="Screen Shot 2024-08-06 at 9 43 24 PM" src="https://github.com/user-attachments/assets/6a3e8842-b2f7-4074-9d9b-0f2e361f7e16">

**Comment by pcwadarong** [comment]
#25 #19 #18
