### ISSUE TITLE
Seperate select styles

### ISSUE THREAD

**Issue by pcwadarong** [BabDeuSilBun/BDSB-frontend#27]
## 📃 Description
![image](https://github.com/user-attachments/assets/ebe41c49-9b18-4cbc-83cc-e2bc9a845d59)
작은 버전에서 디폴드 나오는 문제 발생

저희 select 모양이 한 개인 줄 알았는데 지금 보니 mini 버전으로도 만들어야 할 것 같아서 button처럼 따로 분리해야 할 것 같습니다.

## ☑️ To-Do
![image](https://github.com/user-attachments/assets/3d80d27d-49b6-4e93-ad45-07b665088f2d)

- selector 전역 속성 -> styled components basic selector로 수정
- mini ver 따로 만들기

**Comment by Liz-Chung** [comment]
📃 Description
- name changed from selector to dropdown to avoid confusion with TypeScript selectors
- CustomDropdown
<img width="362" alt="Screen Shot 2024-08-08 at 7 24 02 PM" src="https://github.com/user-attachments/assets/59692a17-c3cf-4431-84ea-d8a6aad33c83">
<img width="356" alt="Screen Shot 2024-08-08 at 7 24 18 PM" src="https://github.com/user-attachments/assets/b2c03c59-bcc4-46c3-83db-7e8bf1de2762">
https://github.com/user-attachments/assets/61239ed2-ff3b-4bcc-b653-41dd8da3e2b4

- SmallCustomDropdown
<img width="172" alt="Screen Shot 2024-08-08 at 7 26 05 PM" src="https://github.com/user-attachments/assets/cd53a6be-e397-47a4-8f7b-9fa368e6f284">
https://github.com/user-attachments/assets/de3b9b61-f5ab-4e1d-ae1f-ef864b480cc8


**Key Differences:**
CustomDropdown: Displays a placeholder when no option is selected. The user must click to select an option.
SmallCustomDropdown: Automatically selects the first option by default and does not display a placeholder. 

Usage Example
```javascript
import React, { useState } from 'react';
import { CustomDropdown, SmallCustomDropdown } from '@/components/common/dropdown';

const DropdownExample = () => {
  const [selectedValue, setSelectedValue] = useState<number | null>(null);
  const [isOpen, setIsOpen] = useState(false);

  const options = [
    { id: 1, name: 'Option 1' },
    { id: 2, name: 'Option 2' },
    // Add more options as needed
  ];

  const handleSelect = (value: number | null) => {
    setSelectedValue(value);
  };

  const handleToggle = () => {
    setIsOpen(prev => !prev);
  };

  return (
    <div>
      <h1>Custom Dropdown</h1>
      <CustomDropdown
        options={options}
        selectedValue={selectedValue}
        onSelect={handleSelect}
        placeholder="Select an option"
        isOpen={isOpen}
        onToggle={handleToggle}
      />

      <h1>Small Custom Dropdown</h1>
      <SmallCustomDropdown
        options={options}
        selectedValue={selectedValue}
        onSelect={handleSelect}
        isOpen={isOpen}
        onToggle={handleToggle}
      />
    </div>
  );
};

export default DropdownExample;
```

☑️ To-Do
- check responsive design

**Comment by pcwadarong** [comment]
> 📃 Description
> 
> * name changed from selector to dropdown to avoid confusion with TypeScript selectors
> * CustomDropdown
> 
> <img alt="Screen Shot 2024-08-08 at 7 24 02 PM" width="362" src="https://private-user-images.githubusercontent.com/141708445/356182256-59692a17-c3cf-4431-84ea-d8a6aad33c83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMjE3MjEsIm5iZiI6MTcyMzEyMTQyMSwicGF0aCI6Ii8xNDE3MDg0NDUvMzU2MTgyMjU2LTU5NjkyYTE3LWMzY2YtNDQzMS04NGVhLWQ4YTZhYWQzM2M4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMjUwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MWVlN2I2YjY4NDhjZTUxOWZlNmM5ZDhkOTdmMWU3MThjMjYyODQxYzRhOGUwYzhmMjQ2NjE2MjJhYmJiN2FjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1ZL8hYD9CLkJ2ewIdtZj09oNSFFVwi5ca1gJPhUrjq4"> <img alt="Screen Shot 2024-08-08 at 7 24 18 PM" width="356" src="https://private-user-images.githubusercontent.com/141708445/356182338-b2c03c59-bcc4-46c3-83db-7e8bf1de2762.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMjE3MjEsIm5iZiI6MTcyMzEyMTQyMSwicGF0aCI6Ii8xNDE3MDg0NDUvMzU2MTgyMzM4LWIyYzAzYzU5LWJjYzQtNDZjMy04M2RiLTdlOGJmMWRlMjc2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMjUwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTVlMDJkZWVlNjRjMTkwODQyZGEyOTBkOTFkOTlkZTI5NzVkMjA2ZjQ4ZWRmZDUzMDA2MDIzNjQ3ZTE1NDJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fExwj8kwAhHIvKGnLGDRLm_6gCIWkLXPyxEeEgBfXss"> https://github.com/user-attachments/assets/61239ed2-ff3b-4bcc-b653-41dd8da3e2b4
> * SmallCustomDropdown
> 
> <img alt="Screen Shot 2024-08-08 at 7 26 05 PM" width="172" src="https://private-user-images.githubusercontent.com/141708445/356182952-cd53a6be-e397-47a4-8f7b-9fa368e6f284.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMjE3MjEsIm5iZiI6MTcyMzEyMTQyMSwicGF0aCI6Ii8xNDE3MDg0NDUvMzU2MTgyOTUyLWNkNTNhNmJlLWUzOTctNDdhNC04ZjdiLTlmYTM2OGU2ZjI4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMjUwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWYzYTBmMjgzMmJjZTVjNjk0ZDFhNzI0MjhhMmFlNzE2MDk0NzZiNmE0NGFmMzJiMDYxNjNmZDNjNzA5MTdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nF7Get7vrJD-LTLQFxJBnvwmbhbm7Ar1OjIBLrCwOhs"> https://github.com/user-attachments/assets/de3b9b61-f5ab-4e1d-ae1f-ef864b480cc8
> **Key Differences:** CustomDropdown: Displays a placeholder when no option is selected. The user must click to select an option. SmallCustomDropdown: Automatically selects the first option by default and does not display a placeholder.
> 
> Usage Example
> 
> ```js
> import React, { useState } from 'react';
> import { CustomDropdown, SmallCustomDropdown } from '@/components/common/dropdown';
> 
> const DropdownExample = () => {
>   const [selectedValue, setSelectedValue] = useState<number | null>(null);
>   const [isOpen, setIsOpen] = useState(false);
> 
>   const options = [
>     { id: 1, name: 'Option 1' },
>     { id: 2, name: 'Option 2' },
>     // Add more options as needed
>   ];
> 
>   const handleSelect = (value: number | null) => {
>     setSelectedValue(value);
>   };
> 
>   const handleToggle = () => {
>     setIsOpen(prev => !prev);
>   };
> 
>   return (
>     <div>
>       <h1>Custom Dropdown</h1>
>       <CustomDropdown
>         options={options}
>         selectedValue={selectedValue}
>         onSelect={handleSelect}
>         placeholder="Select an option"
>         isOpen={isOpen}
>         onToggle={handleToggle}
>       />
> 
>       <h1>Small Custom Dropdown</h1>
>       <SmallCustomDropdown
>         options={options}
>         selectedValue={selectedValue}
>         onSelect={handleSelect}
>         isOpen={isOpen}
>         onToggle={handleToggle}
>       />
>     </div>
>   );
> };
> 
> export default DropdownExample;
> ```
> 
> ☑️ To-Do
> 
> * check responsive design

넘넘 예쁩니다아~~~
