### ISSUE TITLE
Global Styles

### ISSUE THREAD

**Issue by Liz-Chung** [BabDeuSilBun/BDSB-frontend#9]
목표: 디자인 일관성 향상, 반응형 디자인, 다크 모드 지원

파일: src/styles/globals.css

작업 내용:
- `:root` CSS variables
- dark theme colors
- CSS reset, CSS preset
- global css styles 
- input box, text area
- select box
- button
- responsive design (media query)

추가 참고 사항:
필요 시 주석을 추가하여 명확히 해주세요.

**Comment by pcwadarong** [comment]
Connected with #14
